
package com.patriktrefil.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.3
 * Mon Mar 18 15:32:32 CET 2024
 * Generated source version: 3.6.3
 */

@XmlRootElement(name = "createInvoice", namespace = "http://soap.patriktrefil.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createInvoice", namespace = "http://soap.patriktrefil.com/", propOrder = {"arg0", "arg1", "arg2"})

public class CreateInvoice {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;
    @XmlElement(name = "arg2")
    private float arg2;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

    public float getArg2() {
        return this.arg2;
    }

    public void setArg2(float newArg2)  {
        this.arg2 = newArg2;
    }

}

