
package com.patriktrefil.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.3
 * Mon Mar 18 15:32:32 CET 2024
 * Generated source version: 3.6.3
 */

@XmlRootElement(name = "payInvoice", namespace = "http://soap.patriktrefil.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payInvoice", namespace = "http://soap.patriktrefil.com/")

public class PayInvoice {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

